### ISSUE TITLE
privet fails to compile on Ubuntu 14.04.3 LTS

### ISSUE THREAD

**Issue by mceachen** [google/cups-connector#44]
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
$ uname -a
Linux shucks 3.13.0-61-generic #100-Ubuntu SMP Wed Jul 29 11:21:34 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ go get -u github.com/google/cups-connector/connector
# github.com/google/cups-connector/privet
In file included from go/src/github.com/google/cups-connector/privet/avahi.go:12:0:
avahi.h:9:34: fatal error: avahi-client/publish.h: No such file or directory
 #include <avahi-client/publish.h>
                                  ^
compilation terminated.
```

**Comment by jacobmarble** [comment]
`$ sudo apt-get install libavahi-client-dev`

**Comment by mceachen** [comment]
Thanks!

**Comment by jacobmarble** [comment]
No prob. I noticed that same problem just 30m before you opened the issue. Should have left a note in the commit log.
