### PR TITLE
Fix Windows build break in Privet from #237

### PR DESCRIPTION
**Pull request by sicklittlemonkey**
Trivial fixes for Windows build errors introduced in #237:
cups-connector\privet\privet.go:79: too many arguments in call to p.zc.addPrinter
cups-connector\privet\privet.go:105: too many arguments in call to p.zc.updatePrinterTXT

Is Travis CI for Windows still not there yet? Luckily for me the CI catches my Unix build breaks. ; - )

### CODE REVIEW

**Comment by agoode** [comment]
Oops, thanks!
